apiVersion: apps/v1
kind: Deployment
metadata:
  name: spoolman
spec:
  selector:
    matchLabels:
      app: spoolman
  replicas: 1
  template:
    metadata:
      labels:
        app: spoolman
    spec:
      containers:
        - name: spoolman
          image: ghcr.io/donkie/spoolman:latest
          volumeMounts:
            - name: spoolman-volume
              mountPath: /home/app/.local/share/spoolman
      volumes:
        - name: spoolman-volume
          persistentVolumeClaim:
            claimName: spoolman-pvc