---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spoolman-pvc
  labels:
    app: watcharr
spec:
  storageClassName: ceph-filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi