apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: watcharr-public
  annotations: 
    kubernetes.io/ingress.class: traefik-cloudflare
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`watcharr.nitehawk.me`)
      kind: Rule
      services:
        - name: watcharr-web
          port: 3080
  tls:
    secretName: watcharr-public-tls