---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: watcharr-pv-claim
  labels:
    app: watcharr
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi